// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: echo/v1/echo.proto

package echov1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"

	v1 "h3-vs-h2-k6/echo/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EchoServiceName is the fully-qualified name of the EchoService service.
	EchoServiceName = "echo.v1.EchoService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EchoServiceUnaryProcedure is the fully-qualified name of the EchoService's Unary RPC.
	EchoServiceUnaryProcedure = "/echo.v1.EchoService/Unary"
)

// EchoServiceClient is a client for the echo.v1.EchoService service.
type EchoServiceClient interface {
	Unary(context.Context, *connect.Request[v1.EchoRequest]) (*connect.Response[v1.EchoResponse], error)
}

// NewEchoServiceClient constructs a client for the echo.v1.EchoService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEchoServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EchoServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	echoServiceMethods := v1.File_echo_v1_echo_proto.Services().ByName("EchoService").Methods()
	return &echoServiceClient{
		unary: connect.NewClient[v1.EchoRequest, v1.EchoResponse](
			httpClient,
			baseURL+EchoServiceUnaryProcedure,
			connect.WithSchema(echoServiceMethods.ByName("Unary")),
			connect.WithClientOptions(opts...),
		),
	}
}

// echoServiceClient implements EchoServiceClient.
type echoServiceClient struct {
	unary *connect.Client[v1.EchoRequest, v1.EchoResponse]
}

// Unary calls echo.v1.EchoService.Unary.
func (c *echoServiceClient) Unary(ctx context.Context, req *connect.Request[v1.EchoRequest]) (*connect.Response[v1.EchoResponse], error) {
	return c.unary.CallUnary(ctx, req)
}

// EchoServiceHandler is an implementation of the echo.v1.EchoService service.
type EchoServiceHandler interface {
	Unary(context.Context, *connect.Request[v1.EchoRequest]) (*connect.Response[v1.EchoResponse], error)
}

// NewEchoServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEchoServiceHandler(svc EchoServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	echoServiceMethods := v1.File_echo_v1_echo_proto.Services().ByName("EchoService").Methods()
	echoServiceUnaryHandler := connect.NewUnaryHandler(
		EchoServiceUnaryProcedure,
		svc.Unary,
		connect.WithSchema(echoServiceMethods.ByName("Unary")),
		connect.WithHandlerOptions(opts...),
	)
	return "/echo.v1.EchoService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EchoServiceUnaryProcedure:
			echoServiceUnaryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEchoServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEchoServiceHandler struct{}

func (UnimplementedEchoServiceHandler) Unary(context.Context, *connect.Request[v1.EchoRequest]) (*connect.Response[v1.EchoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("echo.v1.EchoService.Unary is not implemented"))
}
